version: '3.8'

services:
  ts-auth-service:
    build:
      context: ./microservices/ts-auth-service-1625
    ports:
      - "1625:1625"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/db1625
    command: ["sh", "-c", "npx prisma generate && npm run seed && npm start"]

  ts-tms-service:
    build:
      context: ./microservices/ts-tms-service-1666
    ports:
      - "1666:1666"
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/db1666
    command: ["sh", "-c", "npx prisma migrate deploy && npx prisma generate && npm start"]

  mysql:
    image: mysql:9.0.1
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: db1625
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql 
      - ./my-sql-init/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data:
