version: '3.8'

services:
  ts-auth-service:
    build:
      context: ./microservices/ts-auth-service-1625
    ports:
      - "3001:3000"  # Expose the service on port 3001

  ts-tms-service:
    build:
      context: ./microservices/ts-tms-service-1666
    ports:
      - "3002:3000"  # Expose the service on port 3002

  ts-notification-service:
    build:
      context: ./microservices/ts-notification-service-1677
    ports:
      - "3003:3000"  # Expose the service on port 3003

  angular-frontend:
    build:
      context: ./frontend/angular-frontend
    ports:
      - "4200:80"  # Expose Angular app on port 4200
