version: '3.8'

services:
  # Eureka Server (Java)
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  # Auth Service (Node.js)
  auth-service:
    build: ./ts-auth-service-1625
    container_name: auth-service
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql-db:3306/auth_db
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - app-network

  # Ticket Management Service (Node.js)
  tms-service:
    build: ./ts-tms-service-1666
    container_name: tms-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysql-db:3306/ticket_db
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - app-network

  # Notification Service (Node.js)
  notification-service:
    build: ./ts-notification-service-1677
    container_name: notification-service
    ports:
      - "4002:4002"
    depends_on:
      - eureka-server
    networks:
      - app-network

  # Angular Frontend
  frontend:
    build: ./frontend
    container_name: angular-frontend
    ports:
      - "80:80"
    networks:
      - app-network

  # Kafka
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app-network
    depends_on:
      - zookeeper

  # MySQL Database
  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
